name: Deploy to firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup the code
        run: npm install
      - name: Generate build
        run: npm run build
      - name: Deploy to Firebase
        run: firebase deploy --token  ${{ secrets.FIREBASE_TOKEN }}
