name: Auto Build

on:
  schedule:
    - cron: "13 3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
          yarn
          sudo yarn global add gatsby-cli
          gatsby build

      - name: Firebase Deploy
        run: |
          sudo yarn global add firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
